name: docs

on:
  # push到main分支时触发
  push:
    branches: [main]

jobs:
  docs:
    if: "contains(github.event.head_commit.message, '[ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: 分支拉取
        uses: actions/checkout@master

      # 使用nodejs 16版本
      - name: 安装node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # 缓存 node_modules
      - name: 缓存node_modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      # 如果缓存没有命中，安装依赖
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      # 运行构建脚本
      - name: 构建
        run: pnpm docs:build

      # 部署
      - name: 部署到github page中
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
